parameters:

services:
    App\Controller\SecurityController:
        arguments:
            $security: '@security.helper'
    _defaults:
        autowire: true      
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

